"""add owasp cwe layer to finding

Revision ID: 3a56f758befd
Revises: 8a07c28c66d9
Create Date: 2026-07-20 15:17:21.674017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3a56f758befd'
down_revision: Union[str, None] = '8a07c28c66d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default="" lets the NOT NULL columns backfill existing rows safely.
    with op.batch_alter_table('finding', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owasp', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=""))
        batch_op.add_column(sa.Column('cwe', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=""))
        batch_op.add_column(sa.Column('layer', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=""))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finding', schema=None) as batch_op:
        batch_op.drop_column('layer')
        batch_op.drop_column('cwe')
        batch_op.drop_column('owasp')

    # ### end Alembic commands ###
