"""add llm scan config to scan

Revision ID: 7c4f9d630e42
Revises: fcdfb0151eb0
Create Date: 2026-07-21 15:47:10.357799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7c4f9d630e42'
down_revision: Union[str, None] = 'fcdfb0151eb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('llm_endpoint', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('llm_body_template', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('llm_response_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan', schema=None) as batch_op:
        batch_op.drop_column('llm_response_path')
        batch_op.drop_column('llm_body_template')
        batch_op.drop_column('llm_endpoint')

    # ### end Alembic commands ###
