"""add finding confidence and priority

Revision ID: 94df12cc3f6f
Revises: e721d9eb6724
Create Date: 2026-07-24 21:18:54.383263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '94df12cc3f6f'
down_revision: Union[str, None] = 'e721d9eb6724'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finding', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confidence', sqlmodel.sql.sqltypes.AutoString(),
                                      nullable=False, server_default="firm"))
        batch_op.add_column(sa.Column('priority', sa.Integer(),
                                      nullable=False, server_default="0"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finding', schema=None) as batch_op:
        batch_op.drop_column('priority')
        batch_op.drop_column('confidence')

    # ### end Alembic commands ###
