"""add second session auth for bola scans

Revision ID: e721d9eb6724
Revises: 7c4f9d630e42
Create Date: 2026-07-21 17:53:11.339826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e721d9eb6724'
down_revision: Union[str, None] = '7c4f9d630e42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auth_headers_b', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan', schema=None) as batch_op:
        batch_op.drop_column('auth_headers_b')

    # ### end Alembic commands ###
