"""add authenticated scanning to scan

Revision ID: fcdfb0151eb0
Revises: 3a56f758befd
Create Date: 2026-07-21 01:02:18.292043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fcdfb0151eb0'
down_revision: Union[str, None] = '3a56f758befd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('authenticated', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('auth_headers', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan', schema=None) as batch_op:
        batch_op.drop_column('auth_headers')
        batch_op.drop_column('authenticated')

    # ### end Alembic commands ###
